config/routes.rb
Rails.application.routes.draw do
  get 'events/streetball'
  get 'events/trainingslager'
  get 'training/trainingszeiten'
  get 'training/hallen'
  get 'training/ansprechpartner'
  get 'home/teams'
  get 'home/partner'
  get 'home/impressum'
  root "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def streetball
  end

  def trainingslager
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  
  def partner
  end

  def teams
  end

   def impressum
  end
end

app/controllers/training_controller.rb
class TrainingController < ApplicationController
  def trainingszeiten
  end

  def hallen
  end

  def ansprechpartner
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/training_helper.rb
module TrainingHelper
end

app/views/events/streetball.html.erb
<div class="wrapper_streetball"> 
       
        <div class= "streetball_2023">
               <%= image_tag "streetball/streetball2023.jpg", size:"1410x750", class:"img"%>
        </div> 

        <div class= "streetball_2023_info">
              <h1> Unser Streetballturnier 2023 </h1> <br>
              <p>In diesem Jahr fand unser 23. Streetballturnier vor dem Oder-Center in Schwedt/Oder statt. Auf vier Courts kämpften 20 Teams aus Brandenburg und Mecklemburg-Vorpommern in ihren Altersklassen um den Sieg. Trotz der Hitze schlugen sich die Basktekballer wacker und beeindruckten die Schaulustigen. In der u12 gewann das Team "---"()......</p>
              <%= link_to "Bilder des Turniers", "https://www.picdrop.com/sebastianhellmuthfotografie/C7nRcTFpGQ" , target: '_blank' , class:"a" %>
              


        </div>

        

    </div> 

app/views/events/trainingslager.html.erb
<div class="wrapper_trainingslager"> 
        <div class= "trainingslager_info">
              <h1>Das BG-94-Trainingslager 2023</h1>
              <p>Auch in diesem Jahr findet unser jährliches BG-Trainingslager in ... statt.</p>
        </div> 
        

        

    </div> 

app/views/home/_footer.html.erb
<footer class="footer">
     <div class="wrapper_footer">
      <div class="row">
        <div class="footer-col">
          <h4>BG 94 Schwedt</h4>
          <ul>
            <li><%= link_to "Home", root_path, class:"a" %></li>
            <li><%= link_to "Impressum", home_impressum_path, class:"a" %></li>
          </ul>
        </div>
        <div class="footer-col">
          <h4>Hilfe</h4>
          <ul>
            <li><%= link_to "Ansprechpartner", training_ansprechpartner_path, class:"a" %></li>
 
          </ul>
        </div>
        <div class="footer-col">
          <h4>online shop</h4>
          <ul>
            <li><%= link_to "Damen", "https://bg94-schwedt.fan12.de/kategorien/damen/", :target => '_blank',class:"a" %></li>
            <li><%= link_to "Herren", "https://bg94-schwedt.fan12.de/kategorien/herren/", :target => '_blank',class:"a" %></li>
            <li><%= link_to "Kinder", "https://bg94-schwedt.fan12.de/kategorien/kinder/", :target => '_blank',class:"a" %></li>
            <li><%= link_to "Accessoires", "https://bg94-schwedt.fan12.de/kategorien/accessoires/", :target => '_blank',class:"a" %></li>
          </ul>
        </div>
        <div class="footer-col">
         <h4>Folge uns!</h4>
          <ul>
            
            <li>
                <%= link_to image_tag("logos/instagram-icon.png", size: "40x40"),  "https://www.instagram.com/bg94schwedt/" ,target: '_blank'%>
            </li>
            <li>
           <%= link_to image_tag("logos/tiktok-icon.png", size: "40x40"),  root_path%>
            </li>
            <li>
            <%= link_to image_tag("logos/facebook-icon.png", size: "40x40"),  "https://www.facebook.com/people/BG94-Schwedt/100063349260929/?locale=de_DE" ,target: '_blank'%>
            </li>      
          </ul>
        </div>
        <div class="credits">
        <br>
        <br>
       
         designed and developed by Linus Pirscher
        </div>

      </div>
     </div>
  </footer>

app/views/home/_header.html.erb
<nav>
        <%= link_to image_tag("logos/bg-logo.png", size: "200x90"),  root_path, class:"logo" %>
        <input type="checkbox" id="toggle_button">
        <label for="toggle_button" class="toggle_button">
            <span class="bar"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </label>
        <ul>
            <li><%= link_to "Home", root_path, class:"a" %></li>
            <li><%= link_to "Teams", home_teams_path, class:"a" %></li>
            <li class="expandable_li">
                <input type="checkbox" id="products_checkbox">
                <label for="products_checkbox">Training  ></label>
                <ul class="dropdown">
                    <li><%= link_to "Trainingszeiten", training_trainingszeiten_path, class:"a" %></li>
                    <li><%= link_to "Sporthallen", training_hallen_path, class:"a" %></li>
                    <li><%= link_to "Ansprechpartner", training_ansprechpartner_path, class:"a" %></li>
                </ul>
            </li>
            <li class="expandable_li">
                <input type="checkbox" id="events_checkbox">
                <label for="events_checkbox">Events ></label>
                <ul class="dropdown">
                    <li> <%= link_to "Streetball", events_streetball_path, class:"a" %></li>
                    <li><%= link_to "Trainingslager", events_trainingslager_path, class:"a" %></li>
                </ul>
            </li>
            <li><%= link_to "Shop", "https://bg94-schwedt.fan12.de/", :target => '_blank',class:"a" %></li>
            <li><%= link_to "Partner", home_partner_path, class:"a" %></li>
            <div class="social_media">
                <%= link_to image_tag("logos/instagram-icon.png", size: "40x40"),  "https://www.instagram.com/bg94schwedt/" ,target: '_blank'%>
            </div>
            <div class="social_media"> <%= link_to image_tag("logos/tiktok-icon.png", size: "40x40"),  root_path%>
            </div>
            <div class="social_media"> <%= link_to image_tag("logos/facebook-icon.png", size: "40x40"),  "https://www.facebook.com/people/BG94-Schwedt/100063349260929/?locale=de_DE" ,target: '_blank'%>
            </div>

           
        </ul>
     
    </nav>

app/views/home/impressum.html.erb
xassa

app/views/home/index.html.erb
<div class="wrapper_home"> 
        <div class="text"><h1>Hallo Sportsfreunde,</h1>
        	<br>
        	<h2>wir sind die BG 94 Schwedt und Basketball ist unsere Leidenschaft.</h2>
        	<br>
        	<p>Hast Du Interesse am Basketball und suchst einen passenden Verein? <br>
        	Dann bist Du hier genau richtig! <br>
        	Wenn Du motiviert und interessiert bist, dann schau einfach mal vorbei.<br>
        	<br>Unsere Teams spielen erfolgreich in Turnieren in ganz Brandenburg. Von den Kleinen, über die Jugend, bis zu den Frauen- und Herren-Teams, bei uns findet jeder etwas. Unsere Trainingszeiten findet Ihr <%= link_to "hier", training_trainingszeiten_path, class:"a" %>.
        	<br>
        	Wie jedes Jahr, findet auch 2023 unser Trainingslager statt. Mehr Infos darüber und zur Anmeldung findet Ihr <%= link_to "hier", events_trainingslager_path, class:"a" %>. 
        	<br>
        	<br>
        	Bis bald und Sport frei!
        	</p>
        </div>
        <div class="blog"><h2>Hier findet ihr aktuelle Ereignisse!</h2> </div>
        <div class="right"> </div>
        <div class="left"> </div>
    </div>

app/views/home/partner.html.erb
sponsoren

app/views/home/sponsoren.html.erb
sponsoren

app/views/home/teams.html.erb
<div class="wrapper_teams"> 
        
        <div class= "u5_img">
                <%= image_tag "https://www.basketsession.com/statics/uploads/2020/05/Chicago-BULLS-1996-72-10.jpg", size:"770x400", class:"img"%>
        </div> 
        <div class= "u5_info">
                <h1>Das ist unsere u5!</h1>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <%= link_to "Spielplan" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
                <%= link_to "Tabelle" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%> 
        </div>
        <div class= "u8_img">
                <%= image_tag "https://www.basketsession.com/statics/uploads/2020/05/Chicago-BULLS-1996-72-10.jpg", size:"770x400", class:"img"%>
        </div> 
        <div class= "u8_info">
                <h1>Das ist unsere u8!</h1>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <%= link_to "Spielplan" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
                <%= link_to "Tabelle" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
        </div>
        <div class= "u12_img">
                <%= image_tag "https://www.basketsession.com/statics/uploads/2020/05/Chicago-BULLS-1996-72-10.jpg", size:"770x400", class:"img"%>
        </div> 
        <div class= "u12_info">
                <h1>Das ist unsere u12!</h1>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <%= link_to "Spielplan" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
                <%= link_to "Tabelle" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
        </div>
        <div class= "u16_img">
                <%= image_tag "https://www.basketsession.com/statics/uploads/2020/05/Chicago-BULLS-1996-72-10.jpg", size:"770x400", class:"img"%>
        </div> 
        <div class= "u16_info">
                <h1>Das ist unsere u16!</h1>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <%= link_to "Spielplan" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
                <%= link_to "Tabelle" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
        </div>
        <div class= "u18_img">
               <%= image_tag "teamfotos/u18-img.png", size:"815x500", class:"img"%>
        </div> 
        <div class= "u18_info">
                <h1>Das ist unsere u18!</h1>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <%= link_to "Spielplan" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
                <%= link_to "Tabelle" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
        </div>
        <div class= "herren_img">
                <%= image_tag "teamfotos/herren-img.png", size:"532x400", class:"img"%>
        </div> 
        <div class= "herren_info">
                <h1>Das ist unsere herren!</h1>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <%= link_to "Spielplan" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
                <%= link_to "Tabelle" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
        </div>
        <div class= "frauen_img">
                <%= image_tag "teamfotos/frauen-img.jpg", size:"465x500", class:"img"%>
        </div> 
        <div class= "frauen_info">
                <h1>Das ist unsere frauen!</h1>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <p>Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! Kurzer Text zum Team! </p> <br>
                <%= link_to "Spielplan" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
                <%= link_to "Tabelle" , "https://bbv-inside.de/spielbetrieb/u18m-oberliga/", target: '_blank' , class:"btn"%>
        </div>
    </div> 

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <title>BG-94-Schwedt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'header', "data-turbo-track": "reload"  %>
    <%= stylesheet_link_tag 'footer', "data-turbo-track": "reload"  %>
    <%= stylesheet_link_tag 'index', "data-turbo-track": "reload"  %>
    <%= stylesheet_link_tag 'teams', "data-turbo-track": "reload"  %>
    <%= stylesheet_link_tag 'hallen', "data-turbo-track": "reload"  %>
    <%= stylesheet_link_tag 'trainingszeiten', "data-turbo-track": "reload"  %>
    <%= stylesheet_link_tag 'ansprechpartner', "data-turbo-track": "reload"  %>
    <%= stylesheet_link_tag 'streetball', "data-turbo-track": "reload"  %>
    <%= stylesheet_link_tag 'trainingslager', "data-turbo-track": "reload"  %>
    <%= javascript_importmap_tags %>
    
  </head>
  <body>
    <div class="grid-container"> 
      <div class="header"> <%= render "home/header" %> </div>
      <div class="main"> <%= yield %> </div>
      <div class="footer"> <%= render "home/footer" %> </div>
    </div>
 

  </body>
</html>

app/views/training/ansprechpartner.html.erb
<div class="wrapper_ansprechpartner"> 
        <div class= "headline"><h1>Hier sind unsere Ansprechpartner!</h1></div>
        <div class= "biden_img">
                <%= image_tag "https://s.abcnews.com/images/Politics/ap_joe_biden_ice_cream_02_floated_jc_141009_16x9_1600.jpg",size:"710x400"%>
        </div> 
        <div class= "biden_info">
               hier stehen schöne sachen wie die kontaktdaten
        </div>
        
    </div> 

app/views/training/hallen.html.erb
<div class="wrapper_hallen"> 
      
        <div class= "dreiklang">
               <%= image_tag "hallen/dreiklanghalle.jpg", size:"533x400", class:"img"%>
        </div> 

        <div class= "dreiklang_info">
              <h3> Sporthalle "Dreiklang" </h3>
              <br>
              Hanns-Eisler-Weg 19
              <br>
              16303 Schwedt/Oder
              <br>
              <br>
              Telefon: 03332 22286
              <br>
              <br>
              <%= link_to 'Sporthalle "Dreiklang" auf Google Maps', "https://www.google.de/maps/place/Sporthalle+Dreiklang/@53.0584181,14.2775634,17z/data=!3m1!4b1!4m6!3m5!1s0x47a9fb49d6d01b33:0x965e9d1b0ad6f3cd!8m2!3d53.0584149!4d14.2801383!16s%2Fg%2F1tknjh8z?hl=de&entry=ttu", target: '_blank' , class:"a" %>


        </div>

        <div class= "neue_zeit">
              
               <%= image_tag "hallen/neuezeit.jpeg", size:"711x400", class:"img"%>
        </div>

        <div class= "neue_zeit_info">
              <h3> Sporthalle "Neue Zeit" </h3>
              <br>
              Ferdinand von Schill Straße 17
              <br>
              16303 Schwedt/Oder 
              <br>
              <br>
              Telefon: 03332 20840
              <br>
              <br>
              <%= link_to 'Sporthalle "Neue Zeit" auf Google Maps', "https://www.google.de/maps/place/Sporthallen+Neue+Zeit/@53.0674133,14.2919473,17z/data=!3m1!4b1!4m6!3m5!1s0x47a9fb43b7ba7ec3:0x1ab18fead53d5210!8m2!3d53.0674133!4d14.294136!16s%2Fg%2F1tdg6v69?hl=de&entry=ttu", target: '_blank', class:"a" %>
        </div>
        <div class= "külzviertel">
                <%= image_tag "hallen/külzviertel.jpg", size:"711x400", class:"img"%>
        </div>

        <div class= "külzviertel_info">
              <h3> Sporthalle "Külzviertel" </h3>
              <br>
              Dr.-Wilhelm-Külz-Viertel 2B
              <br>
              16303 Schwedt/Oder 
              <br>
              <br>
              Telefon: 03332 32215
              <br>
              <br>
              <%= link_to 'Sporthalle "Külzviertel" auf Google Maps', "https://www.google.com/maps/place/Sportplatz+K%C3%BClzviertel/@53.066546,14.2480885,15z/data=!4m6!3m5!1s0x47a9fad831519fe1:0x980640dde8da52d4!8m2!3d53.066546!4d14.2480885!16s%2Fg%2F1tcwvrvd?entry=ttu", target: '_blank', class:"a" %>
        </div>


    </div> 

app/views/training/trainingszeiten.html.erb
<table id="trainingszeiten">
  <tr>
  	<th>Wochentag</th>
    <th>Team</th>
    <th>Uhrzeit</th>
    <th>Halle</th>
    <th>Trainer</th>
  </tr>
  <tr>
    <td>Montag</td>
    <td>Frauen</td>
    <td>20:00 - 21:30</td>
    <td>Sporthalle Dreiklang (groß)</td>
    <td>S. Kasiske/S. Zürner</td>
  </tr>
  <tr>
    <td>Dienstag</td>
    <td>AG Waldrand <br>
      u16
    </td>
    <td>14:30 - 15:30 <br>
      18:30 - 20:00
    </td>
    <td>Külzviertel <br>
    Sporthalle "Neue Zeit"</td>
    <td>U. Schreiber/K. Franz<br>
      U. Schreiber
    </td>
  </tr>
  <tr>
    <td>Mittwoch</td>
    <td>Anfänger/U12<br>
        u16 <br>
        u18
    </td>
    <td>15:30 - 17:00 <br>
        17:00 - 18:30  <br>
        20:00 - 21:30 
    </td>
     <td>Sporthalle Dreiklang (alt)</td>
     <td>T. Lindemann/M. Trojahn<br>
        U. Schreiber<br>
        U. Schreiber/F. Hahn
    </td>
  </tr>
  <tr>
    <td>Donnerstag</td>
    <td>Herren/ü35</td>
    <td>18:30 - 20:00</td>
    <td>Sporthalle Dreiklang (alt)</td>
    <td>E. Pirscher/M. Trojahn</td>
  </tr>
  <tr>
    <td>Freitag</td>
        <td>u16       <br>
        Krabbelgruppe/u5 <br>
        Krabbelgruppe/u8 <br>
        Anfänger/u12  <br>
        u18           <br>
        Herren
    </td>
        <td>13:30 - 15:00<br>
          16:00 - 17:00<br>
          17:00 - 18:00<br>
        17:00 - 18:30<br>
        18:30 - 20:30<br>
        20:00 - 21:30  
    </td>
    <td>Sporthalle Dreiklang (alt)<br>
      Sporthalle Dreiklang (klein)<br>
      Sporthalle Dreiklang (klein)<br>
      Sporthalle Dreiklang (alt)<br>
      Sporthalle Dreiklang (alt)<br>
      Sporthalle Dreiklang (alt)<br>
    </td>
    <td> U. Schreiber<br>
      S. Kasiske/I. Kröhnke<br>
      S. Kasiske/I. Kröhnke<br>
      T. Lindemann/M. Trojahn<br>
      U. Schreiber<br>
      U. Schreiber/F. Hahn
    </td>
  </tr>
  
</table>